apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: go-app-podmonitor
  namespace: monitoring
  labels:
    release: kind-prometheus  
spec:
  namespaceSelector:
    matchNames:
    - default  
  selector:
    matchLabels:
      app: go-app  
  podMetricsEndpoints:
  - port: http  
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s