---
apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: default
  labels:
    app: go-app 
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: go-app
  type: ClusterIP
